//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeUygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Statu { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Deger { get; set; }
    }
}
