//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeUygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> Tutar { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Durum { get; set; }
    }
}
